### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by vaddanki69** [TalSchuster/BiorxivRetriever#2]
Hi,

Once in a while, the following code is hanging/blocking:

    br = BiorxivRetriever()
    papers = br.query("....", metadata=True, full_text=False)

Are there any timeout exceptions that can be thrown, so that we can capture and move on?

Regards

**Comment by TalSchuster** [comment]
Hi. Thanks for your suggestions. Please feel free to submit a pull request and I will review it.

Thank you
