### ISSUE TITLE
When search_engine='rxivist', it does not still show papers from medrxiv

### ISSUE THREAD

**Issue by vaddanki69** [TalSchuster/BiorxivRetriever#3]
br = BiorxivRetriever(search_engine='rxivist')
    papers = br.query("...", metadata=True, full_text=False)

Even, in this case, it shows only papers from Biorxiv but not from Medrxiv.

However, if I make the same query on rxivist web site (downloads, all time, 100 results per page, all repos), I see papers from Medrxiv as well.

You can use "D614G" as the query string to reproduce the problem.

Regards

**Comment by TalSchuster** [comment]
Hi. Thanks for your suggestions. Please feel free to submit a pull request and I will review it.

Thank you
